// Generated by BUCKLESCRIPT VERSION 6.0.1, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/lib/js/src/ReactDOMRe.js");
var Reuniverse = require("./reuniverse.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(Reuniverse.make, { }), "main");

/*  Not a pure module */
