// Generated by BUCKLESCRIPT VERSION 6.0.1, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Reuniverse$Stars(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement("div", {
                  id: "stars"
                }), React.createElement("div", {
                  id: "stars2"
                }), React.createElement("div", {
                  id: "stars3"
                }));
}

var Stars = /* module */[/* make */Reuniverse$Stars];

function Reuniverse$Logo(Props) {
  return React.createElement("img", {
              className: "logo",
              src: "./logo.svg"
            });
}

var Logo = /* module */[/* make */Reuniverse$Logo];

function Reuniverse$Tagline(Props) {
  return React.createElement("span", {
              className: "tagline"
            }, "Package documentation for the entire Reason ecosystem.");
}

var Tagline = /* module */[/* make */Reuniverse$Tagline];

function Reuniverse(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement(Reuniverse$Stars, { }), React.createElement("div", {
                  className: "centered"
                }, React.createElement(Reuniverse$Logo, { }), React.createElement(Reuniverse$Tagline, { })));
}

var make = Reuniverse;

exports.Stars = Stars;
exports.Logo = Logo;
exports.Tagline = Tagline;
exports.make = make;
/* react Not a pure module */
